name: ServerBoards
version: 1.2.1
main: dev.server.boards.ServerBoards
api-version: '26.2'
softdepend: [AuthMe]
commands:
  boards:
    description: 棋类房间和实体棋盘
    permission: serverboards.use
permissions:
  serverboards.use:
    default: true
