package dev.server.boards.rules;

import org.junit.jupiter.api.Test;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;

class NewGamesTest {
    @Test void goScoreNegotiationCannotChangeWhoResumesPlay(){for(int first:new int[]{0,1}){var g=new GoGame(9);g.apply(0,"pass");g.apply(1,"pass");g.apply(first,"accept");g.apply(1-first,"resume");assertEquals(0,g.currentPlayer());}}
    private int[] board(Object game) throws Exception {var f=game.getClass().getDeclaredField("board");f.setAccessible(true);return (int[])f.get(game);}
    private int at(BoardGame game,String id){return game.cells().stream().filter(c->c.id().equals(id)).findFirst().orElseThrow().owner();}
    @Test void reversiOpeningAndIllegalPass(){var g=new ReversiGame();assertEquals(Set.of("place:2,3","place:3,2","place:4,5","place:5,4"),Set.copyOf(g.legalActions(0)));assertThrows(IllegalArgumentException.class,()->g.apply(0,"pass"));g.apply(0,"place:2,3");assertEquals(0,at(g,"3,3"));assertEquals(4,g.cells().stream().filter(c->c.owner()==0).count());assertTrue(g.legalActions(0).isEmpty());}
    @Test void reversiFlipsEveryDirectionAndEndsWhenNeitherCanMove()throws Exception{var g=new ReversiGame();int[] b=board(g);Arrays.fill(b,0);b[0]=-1;b[1]=b[8]=b[9]=1;g.apply(0,"place:0,0");assertTrue(g.finished());assertEquals("winner:0",g.outcome());assertEquals(64,g.cells().stream().filter(c->c.owner()==0).count());}
    @Test void reversiForcedPassDoesNotEndEarly()throws Exception{var g=new ReversiGame();int[] b=board(g);Arrays.fill(b,0);b[0]=b[7]=-1;b[1]=b[6]=1;g.apply(0,"place:0,0");assertFalse(g.finished());assertEquals(0,g.currentPlayer());assertEquals(List.of("place:7,0"),g.legalActions(0));}
    @Test void draughtsOpeningAndMandatoryChain()throws Exception{var g=new DraughtsGame();assertEquals(7,g.legalActions(0).size());int[] b=board(g);Arrays.fill(b,-1);b[1+5*8]=0;b[2+4*8]=1;b[4+2*8]=1;b[7+8]=1;assertEquals(List.of("move:1,5:3,3"),g.legalActions(0));g.apply(0,"move:1,5:3,3");assertEquals(0,g.currentPlayer());assertEquals(List.of("move:3,3:5,1"),g.legalActions(0));g.apply(0,"move:3,3:5,1");assertEquals(1,g.currentPlayer());assertEquals(-1,at(g,"2,4"));assertEquals(-1,at(g,"4,2"));}
    @Test void draughtsCrowningEndsCaptureTurn()throws Exception{var g=new DraughtsGame();int[] b=board(g);Arrays.fill(b,-1);b[1+2*8]=0;b[2+8]=b[4+8]=1;g.apply(0,"move:1,2:3,0");assertEquals(1,g.currentPlayer());assertEquals("王",g.cells().stream().filter(c->c.id().equals("3,0")).findFirst().orElseThrow().piece());assertEquals(1,at(g,"4,1"));}
    @Test void draughtsManCannotCaptureBackwardButKingCan()throws Exception{var g=new DraughtsGame();int[] b=board(g);Arrays.fill(b,-1);b[3+3*8]=0;b[4+4*8]=1;assertFalse(g.legalActions(0).contains("move:3,3:5,5"));b[3+3*8]=2;assertEquals(List.of("move:3,3:5,5"),g.legalActions(0));g.apply(0,"move:3,3:5,5");assertEquals("winner:0",g.outcome());}
    @Test void goCaptureAndSuicide(){var g=new GoGame(9);String[] moves={"1,0","1,1","0,1","8,8","2,1","8,7","1,2"};for(String m:moves)g.apply(g.currentPlayer(),"place:"+m);assertEquals(-1,at(g,"1,1"));assertFalse(g.legalActions(1).contains("place:1,1"));assertThrows(IllegalArgumentException.class,()->g.apply(1,"place:1,1"));}
    @Test void goKoCannotImmediatelyRecreatePosition()throws Exception{var g=new GoGame(9);int[] b=board(g);for(int p:new int[]{0+1*9,1,2+1*9})b[p]=0;for(int p:new int[]{1+1*9,0+2*9,2+2*9,1+3*9})b[p]=1;var f=GoGame.class.getDeclaredField("seen");f.setAccessible(true);@SuppressWarnings("unchecked")Set<String> seen=(Set<String>)f.get(g);seen.clear();StringBuilder key=new StringBuilder();for(int p:b)key.append((char)('0'+p+1));seen.add(key.toString());g.apply(0,"place:1,2");assertEquals(-1,at(g,"1,1"));assertFalse(g.legalActions(1).contains("place:1,1"));}
    @Test void goNeedsBothScoreAgreementsAndCanResume(){var g=new GoGame(9);g.apply(0,"pass");g.apply(1,"pass");assertTrue(g.scoring());assertFalse(g.finished());g.apply(0,"accept");assertFalse(g.finished());g.apply(1,"resume");assertFalse(g.scoring());g.apply(g.currentPlayer(),"pass");g.apply(g.currentPlayer(),"pass");g.apply(0,"accept");g.apply(1,"accept");assertTrue(g.finished());assertEquals("winner:1",g.outcome());assertArrayEquals(new double[]{0,7.5},g.score());}
    @Test void goDeadGroupChangeInvalidatesEarlierAgreement(){var g=new GoGame(9);g.apply(0,"place:0,0");g.apply(1,"place:8,8");g.apply(0,"place:1,0");g.apply(1,"pass");g.apply(0,"pass");g.apply(0,"accept");g.apply(1,"dead:0,0");assertEquals(2,g.cells().stream().filter(c->c.piece().endsWith("×")).count());assertTrue(g.legalActions(0).contains("accept"));g.apply(1,"accept");assertFalse(g.finished());g.apply(0,"accept");assertEquals("winner:1",g.outcome());}
    @Test void yachtCategoryScoringAndBonus()throws Exception{assertEquals(50,YachtGame.score(11,new int[]{6,6,6,6,6}));assertEquals(30,YachtGame.score(10,new int[]{2,3,4,5,6}));assertEquals(15,YachtGame.score(9,new int[]{1,2,3,4,4}));assertEquals(0,YachtGame.score(8,new int[]{2,2,2,2,2}));assertEquals(13,YachtGame.score(8,new int[]{2,2,3,3,3}));assertEquals(25,YachtGame.score(7,new int[]{6,6,6,6,1}));var g=new YachtGame(2,1);var f=YachtGame.class.getDeclaredField("sheet");f.setAccessible(true);int[][] sheet=(int[][])f.get(g);sheet[0]=new int[]{3,6,9,12,15,18,-1,-1,-1,-1,-1,-1};assertEquals(98,g.total(0));}
    @Test void yachtHeldDiceAndThreeRollLimit(){var g=new YachtGame(2,8);g.apply(0,"roll");int first=g.dice()[0];g.apply(0,"hold:die0");g.apply(0,"roll");assertEquals(first,g.dice()[0]);g.apply(0,"roll");assertFalse(g.legalActions(0).contains("roll"));assertFalse(g.legalActions(0).contains("hold:die0"));g.apply(0,"score:ones");assertEquals(1,g.currentPlayer());assertEquals(0,g.rolls());assertFalse(g.held(0));}
    @Test void yachtCompleteGameAndReplayAreDeterministic(){var g=new YachtGame(3,75);var copy=new YachtGame(3,75);for(int n=0;n<36;n++){int seat=g.currentPlayer();for(var item:List.of("roll","hold:die0","roll","score:"+YachtGame.CATEGORIES.get(n/3))){g.apply(seat,item);copy.apply(seat,item);assertEquals(g.cells(),copy.cells());}}assertTrue(g.finished());assertEquals(g.outcome(),copy.outcome());for(int i=0;i<3;i++)assertEquals(g.total(i),copy.total(i));}
    @Test void newFactoryKindsEnforcePlayerCount(){for(String kind:List.of("draughts","reversi","go","go9","go13")){assertNotNull(GameFactory.create(kind,2,3));assertThrows(IllegalArgumentException.class,()->GameFactory.create(kind,3,3));}assertEquals(361,GameFactory.create("go",2,0).cells().size());assertEquals(81,GameFactory.create("go9",2,0).cells().size());assertThrows(IllegalArgumentException.class,()->GameFactory.create("yacht",5,0));}
}
